FROM golang:1.22-alpine as build

WORKDIR /build
RUN apk add make
COPY go.* .
COPY Makefile .
RUN make dep
COPY . .
RUN make

FROM gcr.io/distroless/static-debian12

WORKDIR /app
COPY --from=build /build/bin/tokeniser .
COPY --from=build /build/router/templates router/templates
COPY --from=build /build/router/static router/static

CMD [ "/app/tokeniser" ]