FROM golang:1.22-alpine as build

WORKDIR /build
RUN apk add make
COPY go.* .
COPY Makefile .
RUN make dep
COPY main.go .
COPY src/ ./src/
RUN make

FROM gcr.io/distroless/static-debian12

WORKDIR /app
COPY --from=build /build/bin/tokeniser .
COPY --from=build /build/src/router/templates ./src/router/templates
COPY --from=build /build/src/router/static ./src/router/static

CMD [ "/app/tokeniser" ]