name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    needs: [lint]
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tokeniser:latest

  test:
    runs-on: self-hosted
    steps:
      - name: Run tests
        run: make test

  lint:
    runs-on: self-hosted
    steps:  
      - name: Run lint
        run: make lint
