name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      PASSPHRASE: ${{secrets.PASSPHRASE}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
      POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      APP_PORT: ${{secrets.APP_PORT}}
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.22
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Run tests
        run: make test
