name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Run postgres
        run: docker compose up db -d
      - name: Run tests
        run: make test