name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    needs: [lint]
    runs-on: self-hosted

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tokeniser:0.0.1

  test:
    runs-on: self-hosted
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setting up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - name: Checking directory
        run: ls

      - name: Run tests
        run: make test

  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setting up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - name: Run lint
        run: make lint
