name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    env:
      PASSPHRASE: ${{secrets.PASSPHRASE}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
      POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      APP_PORT: ${{secrets.APP_PORT}}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Run postgres container
        run: docker compose up db -d
      - name: Run tests
        run: make test-ci
